### PR TITLE
Patch for pip v4.19.23

### PR DESCRIPTION
**Pull request by fmauch**
Add private copy operators as required by modern sip.

This would be a solution #2, although not using the proposed method.

### CODE REVIEW

**Comment by fmauch** [comment]
Builds in a clean chroot and dowstream dependencies work with it, so I don't see a reason to use the git version as proposed in #2

**Review by bionade24 — CHANGES_REQUESTED** [review]
Is there any reason to have 2 patches?

**Comment by bionade24** [comment]
Additionally, the `pkgrel` needs to be increased. I did it for the PKGBUILD but forgot to do it for the .SRCINFO.

**Comment by fmauch** [comment]
I updated the `.SRCINFO` file accordingly.

The reason for two patches is that I'm not too familiar with using `patch` as I usually only use `git` directly. But it will be cleaner if we had one patch only, I'll improve that.

**Comment by fmauch** [comment]
OK, merging those patches into one was easier than writing those two comments...

Usually I would go ahead and squash-merge this branch. What is your usual workflow on this @bionade24? Should I do some interactive rebase and force-push to clean up this branch?

**Review by bionade24 — APPROVED** [review]

**Comment by bionade24** [comment]
There is now "workflow" or something like that, the problem is that the AUR has git hook that denies a commit if it doesn't increase the version. Apparrently I merged too fast and now have to rebase, I should have squashed them.

**Comment by fmauch** [comment]
> There is now "workflow" or something like that, the problem is that the AUR has git hook that denies a commit if it doesn't increase the version. Apparrently I merged too fast and now have to rebase, I should have squashed them.

That's good to know.

**Pull request merged**
